In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 6, 4, 5])
arr2 = arr[::-1]

print(arr2)

[5 4 6 3 2 1]


In [3]:
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
array_m1 = array1.flatten()

print(array_m1)

array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
array_m2 = array1.ravel()

print(array_m2)

[1 2 3 2 4 5 1 2 3]
[1 2 3 2 4 5 1 2 3]


In [4]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

are_equal = np.all(arr1 == arr2)
print(are_equal)

True


In [5]:
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
most_frequent_value = np.bincount(x).argmax()
indices = np.where(x == most_frequent_value)[0]
print("Most frequent value in x:", most_frequent_value)
print("Indices of the most frequent value in x:", indices)

Most frequent value in x: 1
Indices of the most frequent value in x: [0 5 7 8 9]


In [7]:
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
most_frequent_value = np.bincount(y).argmax()
indices = np.where(y == most_frequent_value)[0]
print("Most frequent value in y:", most_frequent_value)
print("Indices of the most frequent value in y:", indices)

Most frequent value in y: 1
Indices of the most frequent value in y: [0 1 2]


In [8]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
total_sum = np.sum(gfg)
print("Sum of all elements in gfg:", total_sum)


Sum of all elements in gfg: 45


In [9]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
row_wise_sum = np.sum(gfg, axis=1)
print("Row-wise sum of elements in gfg:")
print(row_wise_sum)

Row-wise sum of elements in gfg:
[[14]
 [16]
 [15]]


In [10]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
column_wise_sum = np.sum(gfg, axis=0)
print("Column-wise sum of elements in gfg:")
print(column_wise_sum)

Column-wise sum of elements in gfg:
[[20  9 16]]


In [11]:
n_array = np.array([[55, 25, 15],
                    [30, 44, 2],
                    [11, 45, 77]])
diagonal_sum = np.sum(np.diagonal(n_array))
print("Sum of diagonal elements in n_array:", diagonal_sum)

Sum of diagonal elements in n_array: 176


In [12]:
n_array = np.array([[55, 25, 15],
                    [30, 44, 2],
                    [11, 45, 77]])
eigenvalues = np.linalg.eigvals(n_array)
print("Eigenvalues of the matrix n_array:")
print(eigenvalues)

Eigenvalues of the matrix n_array:
[98.16835147 28.097044   49.73460452]


In [13]:
n_array = np.array([[55, 25, 15],
                    [30, 44, 2],
                    [11, 45, 77]])
eigenvalues, eigenvectors = np.linalg.eig(n_array)
print("\nEigenvectors of the matrix n_array:")
print(eigenvectors)


Eigenvectors of the matrix n_array:
[[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]


In [14]:
n_array = np.array([[55, 25, 15],
                    [30, 44, 2],
                    [11, 45, 77]])
inverse_matrix = np.linalg.inv(n_array)
print("Inverse of the matrix n_array:")
print(inverse_matrix)

Inverse of the matrix n_array:
[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]


In [15]:
n_array = np.array([[55, 25, 15],
                    [30, 44, 2],
                    [11, 45, 77]])
determinant = np.linalg.det(n_array)
print("Determinant of the matrix n_array:")
print(determinant)

Determinant of the matrix n_array:
137180.0000000001


In [17]:
p = np.array([[1, 2], [2, 3]])
q = np.array([[4, 5], [6, 7]])
product = np.dot(p, q)
print("Product of matrices p and q:")
print(product)

Product of matrices p and q:
[[16 19]
 [26 31]]


In [18]:
p = np.array([[1, 2], [2, 3]])
q = np.array([[4, 5], [6, 7]])
p_flat = p.flatten()
q_flat = q.flatten()
covariance_matrix = np.cov(p_flat, q_flat)
print("Covariance matrix between flattened p and q:")
print(covariance_matrix)

Covariance matrix between flattened p and q:
[[0.66666667 1.        ]
 [1.         1.66666667]]


In [20]:
p = np.array([[1, 2], [2, 3], [4, 5]])
q = np.array([[4, 5, 1], [6, 7, 2]])
product = np.dot(p, q)
print("Product of matrices p and q:")
print(product)
p_flat = p.flatten()
q_flat = q.flatten()
covariance_matrix = np.cov(p_flat, q_flat)
print("Covariance matrix between flattened p and q:")
print(covariance_matrix)

Product of matrices p and q:
[[16 19  5]
 [26 31  8]
 [46 55 14]]
Covariance matrix between flattened p and q:
[[2.16666667 0.23333333]
 [0.23333333 5.36666667]]


In [21]:
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
inner_product = np.inner(x, y)
print("Inner product of matrices x and y:")
print(inner_product)

outer_product = np.outer(x, y)
print("\nOuter product of matrices x and y:")
print(outer_product)

cartesian_product = np.array(np.meshgrid(x.flatten(), y.flatten())).T.reshape(-1, 2)
print("\nCartesian product of matrices x and y:")
print(cartesian_product)

Inner product of matrices x and y:
[[17 52]
 [13 62]]

Outer product of matrices x and y:
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]

Cartesian product of matrices x and y:
[[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]


In [22]:
array = np.array([[1, -2, 3], [-4, 5, -6]])
abs_array = np.abs(array)
print(abs_array)

[[1 2 3]
 [4 5 6]]


In [23]:
array = np.array([[1, -2, 3], [-4, 5, -6]])
flattened_percentiles = np.percentile(array, [25, 50, 75])
print("Percentiles of the flattened array:", flattened_percentiles)
column_percentiles = np.percentile(array, [25, 50, 75], axis=0)
print("Percentiles for each column:\n", column_percentiles)
row_percentiles = np.percentile(array, [25, 50, 75], axis=1)
print("Percentiles for each row:\n", row_percentiles)

Percentiles of the flattened array: [-3.5 -0.5  2.5]
Percentiles for each column:
 [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
Percentiles for each row:
 [[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]


In [24]:
array = np.array([[1, -2, 3], [-4, 5, -6]])
flattened_mean = np.mean(array)

flattened_median = np.median(array)

flattened_std = np.std(array)

print("Flattened array - Mean:", flattened_mean)
print("Flattened array - Median:", flattened_median)
print("Flattened array - Standard Deviation:", flattened_std)

column_mean = np.mean(array, axis=0)

column_median = np.median(array, axis=0)

column_std = np.std(array, axis=0)

print("Column-wise - Mean:\n", column_mean)
print("Column-wise - Median:\n", column_median)
print("Column-wise - Standard Deviation:\n", column_std)

row_mean = np.mean(array, axis=1)

row_median = np.median(array, axis=1)

row_std = np.std(array, axis=1)

print("Row-wise - Mean:\n", row_mean)
print("Row-wise - Median:\n", row_median)
print("Row-wise - Standard Deviation:\n", row_std)

Flattened array - Mean: -0.5
Flattened array - Median: -0.5
Flattened array - Standard Deviation: 3.8622100754188224
Column-wise - Mean:
 [-1.5  1.5 -1.5]
Column-wise - Median:
 [-1.5  1.5 -1.5]
Column-wise - Standard Deviation:
 [2.5 3.5 4.5]
Row-wise - Mean:
 [ 0.66666667 -1.66666667]
Row-wise - Median:
 [ 1. -4.]
Row-wise - Standard Deviation:
 [2.05480467 4.78423336]


In [25]:
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])

floor_values = np.floor(a)

ceiling_values = np.ceil(a)

truncated_values = np.trunc(a)

rounded_values = np.round(a)

print("Original array:", a)
print("Floor values:", floor_values)
print("Ceiling values:", ceiling_values)
print("Truncated values:", truncated_values)
print("Rounded values:", rounded_values)

Original array: [-1.8 -1.6 -0.5  0.5  1.6  1.8  3. ]
Floor values: [-2. -2. -1.  0.  1.  1.  3.]
Ceiling values: [-1. -1. -0.  1.  2.  2.  3.]
Truncated values: [-1. -1. -0.  0.  1.  1.  3.]
Rounded values: [-2. -2. -0.  0.  2.  2.  3.]


In [27]:
array = np.array([10, 52, 62, 16, 16, 54, 453])
sorted_array = np.sort(array)
print("Sorted array:", sorted_array)
sorted_indices = np.argsort(array)
print("Indices of sorted array:", sorted_indices)
four_smallest = np.sort(array)[:4]
print("4 smallest elements:", four_smallest)
five_largest = np.sort(array)[-5:][::-1]
print("5 largest elements:", five_largest)

Sorted array: [ 10  16  16  52  54  62 453]
Indices of sorted array: [0 3 4 1 5 2 6]
4 smallest elements: [10 16 16 52]
5 largest elements: [453  62  54  52  16]


In [28]:
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
integer_elements = array[np.modf(array)[0] == 0]
print("Integer elements only:", integer_elements)
float_elements = array[np.modf(array)[0] != 0]
print("Float elements only:", float_elements)

Integer elements only: [1. 2. 3. 2.]
Float elements only: [1.2 2.2]


In [36]:
from PIL import Image
import numpy as np
import os

def img_to_array(path):
    if not os.path.isfile(path):
        print(f"Error: The file at path {path} does not exist.")
        return
    try:
        with Image.open(path) as img:
            img_array = np.array(img)
            if len(img_array.shape) == 2:
                mode = 'grayscale'
                file_name = f"{mode}_image_array.txt"
                np.savetxt(file_name, img_array, fmt='%d', delimiter=',')
            
            elif len(img_array.shape) == 3 and img_array.shape[2] == 3:
                mode = 'rgb'
                for i, color in enumerate(['R', 'G', 'B']):
                    channel_array = img_array[:, :, i]
                    file_name = f"{mode}_{color}_channel.txt"
                    np.savetxt(file_name, channel_array, fmt='%d', delimiter=',')
            
            else:
                raise ValueError("Unsupported image format")
            
            print(f"Image array saved to text files for {mode} image")

    except Exception as e:
        print(f"An error occurred: {e}")
img_to_array(r'D:\shouts-animals-watch-baby-hemingway.png')



Image array saved to text files for rgb image


In [37]:
from PIL import Image
import numpy as np
import os

def img_to_array(path):
    if not os.path.isfile(path):
        print(f"Error: The file at path {path} does not exist.")
        return
    try:
        with Image.open(path) as img:
            img_array = np.array(img)
            if len(img_array.shape) == 2:
                mode = 'grayscale'
                file_name = f"{mode}_image_array.txt"
                np.savetxt(file_name, img_array, fmt='%d', delimiter=',')
            
            elif len(img_array.shape) == 3 and img_array.shape[2] == 3:
                mode = 'rgb'
                for i, color in enumerate(['R', 'G', 'B']):
                    channel_array = img_array[:, :, i]
                    file_name = f"{mode}_{color}_channel.txt"
                    np.savetxt(file_name, channel_array, fmt='%d', delimiter=',')
            
            else:
                raise ValueError("Unsupported image format")
            
            print(f"Image array saved to text files for {mode} image")

    except Exception as e:
        print(f"An error occurred: {e}")
img_to_array(r'D:\B2DBy.jpg')


Image array saved to text files for rgb image
